apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  username: ZXNw
  password: ZXNwX2luX2Nsb3Vk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  PGDATA: /mnt/data/postgres
---
kind: Service
apiVersion: v1 
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP            # TCP
      targetPort: 5432
      port: 80              
  type: ClusterIP
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: postgres
  template:
       metadata:
         annotations:
           seccomp.security.alpha.kubernetes.io/pod: runtime/default
         labels:
           app: postgres
       spec:
         TEMPLATE_ESP_AZUREimagePullSecrets:
         TEMPLATE_ESP_AZURE  - name: acr-secret         
         TEMPLATE_ESP_NOAZUREsecurityContext:
         TEMPLATE_ESP_NOAZURE  runAsUser:  1001
         TEMPLATE_ESP_NOAZURE  runAsGroup: 1001
         containers:
         - name: postgres
           image: postgres:10.4
           ports:
             - containerPort: 5432  # servers REST port
               name: postgresdb
           env:
             - name: POSTGRES_USER
               valueFrom:
                 secretKeyRef:
                   name: postgres-secret
                   key:  username
             - name: POSTGRES_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: postgres-secret
                   key:  password
           envFrom:
             - configMapRef: 
                name: postgres-config
           volumeMounts:
              - name: data            # the volume specified below
                mountPath: /mnt/data  # path persistent volume gets mounted to
           securityContext:
             allowPrivilegeEscalation: false
             #readOnlyRootFilesystem: true
         initContainers:
         - name: config-data
           image: busybox
           #
           # Our nfs PV is owned by sas:sas which is 1001:1001, so
           #    use those credentials to make <namespace>/{DB,input,output}
           #    directories.
           #
           TEMPLATE_ESP_NOAZUREsecurityContext:
           TEMPLATE_ESP_NOAZURE  runAsUser:  1001
           TEMPLATE_ESP_NOAZURE  runAsGroup: 1001
           command: ['sh', '-c', 'mkdir -p /mnt/data/postgres']
           volumeMounts:
           - name: data
             mountPath: /mnt/data
         volumes:
           - name: data
             persistentVolumeClaim:
               claimName: esp-pv-pg
 #          - name: postgres-init
 #            configMap:
 #              name: espdb-config
 #              items:
 #              - key: init-esp.sh
 #                path: init-esp.sh
            
