#
# This is the esp-pv claim that esp component pods make use of.
#
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
   name: esp-pv-pg
   annotations:
     volume.beta.kubernetes.io/storage-class: "nfs-client"   
spec:
   accessModes:
     - ReadWriteOnce # This volume is used for Postgres storage
   resources:
     requests:
       storage: 10Gi  # volume size requested
