kind: Service
apiVersion: v1
metadata:
  name: sas-event-stream-manager-app
spec:
  selector:
    app: sas-event-stream-manager-app
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sas-event-stream-manager-app
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
spec:
  rules:
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: sas-event-stream-manager-app # the service to hit
          servicePort: 80            # externally exposed port
        path: /SASEventStreamManager
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sas-event-stream-manager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sas-event-stream-manager-app
  template:
    metadata:
      labels:
        app: sas-event-stream-manager-app
    spec:
      serviceAccountName: esp-operator
      containers:
      - name: esm-container
        image: TEMPLATE_ESM_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SAS_VIYA_ENABLED
          value: "false"
        - name: SAS_MULTI_TENANCY_ENABLED
          value: "true"
        - name: ESM_LICENSE_FILE
          value: "/opt/sas/viya/config/etc/sysconfig/sas-esm-service/default/license.txt"
        - name: SAS_ESP_COMMON_KUBERNETES
          value: "true"
        - name: SAS_ESP_COMMON_KUBERNETES_NAMESPACE
          value: TEMPLATE_ESP_NAMESPACE
        #
        # Below is the postgres configuration
        #
        - name: spring_datasource_url
          value: "jdbc:postgresql://postgres-service:80/esp"
        - name: spring_datasource_username
          value: "esp"
        - name: spring_datasource_password
          value: "esp_in_cloud"
        - name: spring_datasource_platform
          value: "postgresql"
        - name: spring_datasource_driver_class_name
          value: "org.postgresql.Driver"
        #
        # END postgres config
        #
        volumeMounts:
           - mountPath: "/opt/sas/viya/config/etc/sysconfig/sas-esm-service/default"
             name: esm-license
             readOnly: false
      volumes:
        - name: esm-license
          secret:
            secretName: esm-license
