apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: espstudio
  namespace: TEMPLATE_ESP_NAMESPACE
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
spec:
  rules:
  - host: espstudio.TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      -  backend:
          serviceName: espstudio-service # the service to hit
          servicePort: 80            # externally exposed port

