apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: espupdates.iot.sas.com
spec:
  group: iot.sas.com
  names:
    kind: ESPUpdate
    listKind: ESPUpdateList
    plural: espupdates
    singular: espupdate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ESPUpdate is the Schema for the espupdates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ESPUpdateSpec defines the desired state of ESPUpdate
            type: object
            properties:
              policy:
                type: string
              gracePeriod:
                type: string
                nullable: true
              selector:
                type: string
                nullable: true
          status:
            description: ESPUpdateStatus defines the observed state of ESPUpdate
            type: object
          response:
            description: ESPUpdateResponse defines the response of ESPUpdate
            nullable: true
            type: object
            properties:
              succeeded:
                type: boolean
                nullable: true
              reason:
                type: string
                nullable: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
