apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: espservers.iot.sas.com
spec:
  group: iot.sas.com
  names:
    kind: ESPServer
    listKind: ESPServerList
    plural: espservers
    singular: espserver
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        access:
          properties:
            externalURL:
              type: string
            internalHostName:
              type: string
            internalHttpPort:
              format: int64
              type: integer
            state:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          type: object
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoscale:
              properties:
                maxReplicas:
                  format: int32
                  type: integer
                metrics:
                  items:
                    type: object
                  type: array
                minReplicas:
                  format: int32
                  type: integer
              required:
              - minReplicas
              - maxReplicas
              - metrics
              type: object
            env:
              nullable: true
              items:
                type: object
              type: array
            espProperties:
              nullable: true
              additionalProperties:
                type: string
              type: object
            failover:
              type: boolean
            loadBalancePolicy:
              type: string
            loadBalancer:
              nullable: true
              properties:
                env:
                  nullable: true
                  items:
                    type: object
                  type: array
                replicas:
                  nullable: true
                  description: Loadbalancer specification
                  format: int64
                  type: integer
                resources:
                  nullable: true
                  type: object
                targets:
                  nullable: true
                  items:
                    properties:
                      connectors:
                        nullable: true
                        items:
                          properties:
                            class:
                              type: string
                            properties:
                              additionalProperties:
                                type: string
                              type: object
                            type:
                              description: connectors optionally define how data come
                                into the load balancer
                              type: string
                          required:
                          - class
                          - properties
                          type: object
                        type: array
                      queryName:
                        type: string
                      schema:
                        properties:
                          fields:
                            items:
                              properties:
                                key:
                                  type: string
                                name:
                                  type: string
                                type:
                                  type: string
                              required:
                              - name
                              - type
                              type: object
                            type: array
                        type: object
                      schemaString:
                        type: string
                      type:
                        type: string
                      windowName:
                        type: string
                    required:
                    - queryName
                    - windowName
                    - connectors
                    type: object
                  type: array
              required:
              - targets
              type: object
            model:
              type: string
            name:
              type: string
            replicas:
              format: int64
              type: integer
            resources:
              type: object
            volumeMounts:
              nullable: true
              items:
                type: object
              type: array
            volumes:
              nullable: true
              items:
                type: object
              type: array
          required:
          - replicas
          - espProperties
          - resources
          - autoscale
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
