kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-ingress-esp-operator
  namespace: TEMPLATE_ESP_NAMESPACE
rules:
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - autoscaling 
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-ingress-TEMPLATE_ESP_NAMESPACE
subjects:
- kind: ServiceAccount
  name: esp-operator
  namespace: TEMPLATE_ESP_NAMESPACE 
roleRef:
  kind: ClusterRole
  name: nginx-ingress-esp-operator
  apiGroup: rbac.authorization.k8s.io

