apiVersion: v1
kind: Secret
metadata:
  name: sas-license-secret
  namespace: TEMPLATE_ESP_NAMESPACE
type: Opaque
data:
  # Writing out pre-defined secrets
  SAS_LICENSE: TEMPLATE_ESP_LICB64
---
apiVersion: v1
kind: Secret
metadata:
  name: sas-ca-cert-secret
  namespace: TEMPLATE_ESP_NAMESPACE
type: Opaque
data:
  SAS_CA_CERT: TEMPLATE_ESP_CERTB64
