apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metering
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    
spec:
  rules:
  - host: TEMPLATE_ESP_NAMESPACE.TEMPLATE_ESP_DOMAIN
    http:
      paths:
      - backend:
          serviceName: espmeter-service # the service to hit
          servicePort: 80               # externally exposed port 
        path: /SASEventStreamProcessingMetering(/|$)(.*)
