kind: Service
apiVersion: v1 
metadata:
  name: espmeter-service
  namespace: TEMPLATE_ESP_NAMESPACE            # all objects are in TEMPLATE_ESP_NAMESPACE
spec:
  selector:
    app: espmeter               # target any pod with the app=espmeter label
  ports:
    - protocol: TCP             # TCP
      targetPort: 31415         # the port esp exposes on the pod it runs in
      port: 80                  # the port within the K8 cluster
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: TEMPLATE_ESP_NAMESPACE            # all objects are in my own namespace "sjk"
  name: espmeter-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: espmeter
  template:
       metadata:
         labels:
           app: espmeter
       spec:
         containers:
         - name: espmetering-container
           image: TEMPLATE_ESP_METER_IMAGE
           env:
             # METER_PORT specifies REST endpoint for metering server.
             # METER_DB   specifies location of H2 database.
             #
             - name: METER_PORT
               value: "31415"
             - name: METER_DB
               value: "/mnt/data/TEMPLATE_ESP_NAMESPACE/DB/metering"
             #- name: ESP_BILLING_ENABLED
             #  value: "true"
             #- name: ESPMETERING
             #  value: "/mnt/data/TEMPLATE_ESP_NAMESPACE/billing"
             #(only for debugging) - name: ESPMETERING_TEST
             #   value: "true"
           ports:
             - containerPort: 31415   # servers REST port
               name: http
           volumeMounts:
              - mountPath: /mnt/data  # path persistent volume gets mounted to
                name: data            # the volume specified below
         initContainers:
         - name: config-data
           image: busybox
           #
           # Our nfs PV is owned by sas:sas which is 1001:1001, so
           #    use those credentials to make <namespace>/{DB,input,output}
           #    directories.
           #
           securityContext:
             runAsUser:  1001
             runAsGroup: 1001
           command: ['sh', '-c', 'mkdir /mnt/data/TEMPLATE_ESP_NAMESPACE/billing; mkdir -p /mnt/data/TEMPLATE_ESP_NAMESPACE/DB ; mkdir -p /mnt/data/TEMPLATE_ESP_NAMESPACE/input ; mkdir -p /mnt/data/TEMPLATE_ESP_NAMESPACE/output']
           volumeMounts:
           - mountPath: /mnt/data
             name: data
         volumes:
           - name: data
             persistentVolumeClaim:
               claimName: esp-pv
