kind: Service
apiVersion: v1 
metadata:
  name: espmeter-service
spec:
  selector:
    app: espmeter               # target any pod with the app=espmeter label
  ports:
    - protocol: TCP             # TCP
      targetPort: 31415         # the port esp exposes on the pod it runs in
      port: 80                  # the port within the K8 cluster
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espmeter-deployment
spec:
  replicas: 1
  selector:
     matchLabels:
       app: espmeter
  template:
       metadata:
         labels:
           app: espmeter
       spec:
         containers:
         - name: espmetering-container
           image: TEMPLATE_ESP_METER_IMAGE
           env:
             - name: server_port
               value: "31415"
             - name: spring_datasource_url
               value: "jdbc:postgresql://postgres-service:80/esp"
             - name: spring_datasource_username
               value: "esp"
             - name: spring_datasource_password
               value: "esp_in_cloud"
             - name: spring_datasource_platform
               value: "postgresql"
             - name: spring_datasource_driver_class_name
               value: "org.postgresql.Driver"
             - name: file_encoding
               value: "UTF-8"
           ports:
             - containerPort: 31415   # servers REST port
               name: http
